name: Push Test
# This workflow is triggered on pushes to the repository.
on: [push,pull_request]

jobs:
  build:
    # Job name is Pushing
    name: Pushing
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Checkout
        uses: actions/checkout@v3
       
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm install -g bats
      - run: bats -v

      - name: Installing Dependencies
        run: yarn install
      
      - name: Running Lint
        run: yarn lint
      
      - name: Running Test
        run: yarn test