name: Action Test
on: 
  pull_request: 
    branches: ["main"]

jobs:
  - name: progran Test
  - runs-on: ubuntu-lastest
  steps:
    - run: echo "?The job was automatically triggered by a ${{github.event_name}} event."
    - name: Checkout repository code
    - uses: action/checkout@v2
